import pygame

WINDOW_SIZE = (800, 450)
WINDOW_FLAG = pygame.RESIZABLE
# WINDOW_FLAG = pygame.RESIZABLE | pygame.SCALED
WINDOW_CAPTION = "Card Dungeon"

ZOOM = 2

MAP_SIZE_X = 50
MAP_SIZE_Y = 50
TILE_PIXEL = 16
